# Generated by Django 2.1.15 on 2020-11-18 01:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=80)),
                ('last_name', models.CharField(max_length=80)),
                ('email', models.EmailField(max_length=254)),
            ],
            options={
                'db_table': 'author',
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isbn', models.CharField(max_length=13)),
                ('title', models.CharField(max_length=150)),
                ('publication_date', models.DateField()),
                ('date_created', models.DateTimeField(verbose_name='date created')),
                ('firm_sale', models.BooleanField(default=False)),
                ('no_discounting', models.BooleanField(default=False)),
                ('no_special_orders', models.BooleanField(default=False)),
                ('generic_item', models.BooleanField(default=False)),
                ('available', models.SmallIntegerField(default=0)),
                ('on_hand', models.SmallIntegerField(default=0)),
                ('draft', models.SmallIntegerField(default=0)),
                ('holds', models.SmallIntegerField(default=0)),
                ('special_orders', models.SmallIntegerField(default=0)),
                ('approval', models.SmallIntegerField(default=0)),
                ('on_order', models.SmallIntegerField(default=0)),
                ('layby', models.SmallIntegerField(default=0)),
                ('backorder', models.SmallIntegerField(default=0)),
                ('minimum_number', models.SmallIntegerField(default=0)),
                ('maximum_number', models.SmallIntegerField(default=0)),
                ('retail_value', models.DecimalField(decimal_places=2, max_digits=8)),
                ('sell_value', models.DecimalField(decimal_places=2, max_digits=8)),
                ('cost_including_gst_value', models.DecimalField(decimal_places=2, max_digits=8)),
                ('cost_excluding_gst_value', models.DecimalField(decimal_places=2, max_digits=8)),
                ('margin', models.DecimalField(decimal_places=2, max_digits=8)),
                ('notes', models.TextField()),
                ('dewey_decimal_class', models.DecimalField(decimal_places=6, max_digits=16)),
                ('language', models.CharField(max_length=80)),
                ('number_of_pages', models.SmallIntegerField(default=0)),
                ('height_in_millimetres', models.DecimalField(decimal_places=2, max_digits=5)),
                ('width_in_millimetres', models.DecimalField(decimal_places=2, max_digits=5)),
                ('image_path_local', models.CharField(max_length=150)),
                ('image_path_remote', models.URLField(max_length=250)),
                ('book_format', models.CharField(choices=[('PB', 'Paperback'), ('HB', 'Hardback'), ('TP', 'Trade Paperback'), ('BX', 'Boxed Set'), ('MC', 'Miscellaneous'), ('CA', 'Card')], default='PB', max_length=2)),
                ('book_status', models.CharField(choices=[('ACT', 'Active'), ('OP', 'Out of Print'), ('SHT', "It's Shit"), ('JAN', 'Due January'), ('FEB', 'Due February'), ('MAR', 'Due March'), ('APR', 'Due April'), ('MAY', 'Due May'), ('JUN', 'Due June'), ('JUL', 'Due July'), ('AUG', 'Due August'), ('SEP', 'Due September'), ('OCT', 'Due October'), ('NOV', 'Due November'), ('DEC', 'Due December'), ('POD', 'Print on Demand'), ('CAN', 'Cancelled')], default='ACT', max_length=3)),
                ('authors', models.ManyToManyField(to='dust.Author')),
            ],
            options={
                'db_table': 'book',
            },
        ),
        migrations.CreateModel(
            name='Imprint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('website', models.URLField()),
            ],
            options={
                'db_table': 'imprint',
            },
        ),
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('address', models.CharField(max_length=100)),
                ('suburb', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=80)),
                ('country', models.CharField(max_length=80)),
                ('website', models.URLField()),
                ('imprints', models.ManyToManyField(to='dust.Imprint')),
            ],
            options={
                'db_table': 'publisher',
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('address', models.CharField(max_length=100)),
                ('suburb', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=80)),
                ('country', models.CharField(max_length=80)),
                ('website', models.URLField()),
                ('publishers', models.ManyToManyField(to='dust.Publisher')),
            ],
            options={
                'db_table': 'supplier',
            },
        ),
        migrations.AddField(
            model_name='book',
            name='imprint',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='dust.Imprint'),
        ),
        migrations.AddField(
            model_name='book',
            name='publisher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='dust.Publisher'),
        ),
        migrations.AddField(
            model_name='book',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='dust.Supplier'),
        ),
    ]
