# Generated by Django 2.1.15 on 2020-11-18 02:25

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('dust', '0002_author_date_added'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='date_added',
            field=models.DateTimeField(verbose_name=datetime.datetime(2020, 11, 18, 2, 25, 5, 706029, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='author',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
